# Generated by Django 5.1.3 on 2025-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_bookingpayments_booking_payments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_payments',
            old_name='service_payment_id',
            new_name='payment_id',
        ),
    ]
