# Generated by Django 5.1.3 on 2025-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_service_payment_id_service_payments_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_payments',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=15),
        ),
    ]
