# Generated by Django 5.1.3 on 2025-02-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_booking_payments_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_payments',
            old_name='payment_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='service_payments',
            old_name='payment_date',
            new_name='ordered',
        ),
    ]
