# Generated by Django 5.1.3 on 2025-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payment_date_booking_payments_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_payments',
            old_name='ordered',
            new_name='ordered_on',
        ),
        migrations.AlterField(
            model_name='service_payments',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=15),
        ),
    ]
