# Generated by Django 5.1.3 on 2025-02-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_ordered_service_payments_ordered_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_payments',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='service_payments',
            name='payment_method',
        ),
    ]
