# Generated by Django 5.1.3 on 2025-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_booking_payments_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_payments',
            name='bank_name',
        ),
    ]
