# Generated by Django 5.1.3 on 2025-02-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_customer_order'),
        ('payments', '0008_remove_booking_payments_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='cashier.customer')),
            ],
        ),
    ]
