# Generated by Django 5.1.3 on 2024-11-13 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.CharField(default='temp001', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='0000000000', max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('role', models.CharField(choices=[('Receptionist', 'Receptionist'), ('Stock Manager', 'Stock Manager'), ('System Admin', 'System Admin'), ('Cashier', 'Cashier'), ('Security', 'Security'), ('Waiter', 'Waiter'), ('Waitress', 'Waitress')], max_length=30)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
