# Generated by Django 5.1.3 on 2024-11-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE login_employee MODIFY employee_id VARCHAR(50) "
                "DEFAULT 'temp001' UNIQUE;"
            ),
            reverse_sql=(
                "ALTER TABLE login_employee MODIFY employee_id VARCHAR(50);"
            ),
        ),
    ]