# Generated by Django 5.1.3 on 2024-11-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(
                blank=True, default='temp001', max_length=50, unique=True),
        ),
    ]
