# Generated by Django 5.1.3 on 2024-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_employee_id_alter_employee_employee_id'),
    ]

    operations = [
    ]
