# Generated by Django 5.1.3 on 2024-11-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Stock Manager', 'Stock Manager'), ('Cashier', 'Cashier'), ('Security', 'Security'), ('Waiter', 'Waiter'), ('Waitress', 'Waitress')], max_length=30),
        ),
    ]
