# Generated by Django 5.1.3 on 2025-01-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_bank_name_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
    ]
