# Generated by Django 5.1.3 on 2025-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
