# Generated by Django 5.1.3 on 2025-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Checked-out', 'Checked-out')], default='Pending', max_length=15),
        ),
    ]
