# Generated by Django 5.1.3 on 2025-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Checked-In', 'Checked-In'), ('Pending', 'Pending'), ('Checked-Out', 'Checked-Out')], default='Pending', max_length=15),
        ),
    ]
