# Generated by Django 5.1.3 on 2025-02-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0008_remove_booking_payments_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking')], max_length=15)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Successfull', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('booking_payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='payments.booking_payments')),
                ('service_payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to='payments.service_payments')),
            ],
        ),
    ]
