# Generated by Django 5.1.3 on 2025-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0002_delete_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('item_type', models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks')], max_length=15)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
